### ISSUE TITLE
Test failing to capture output to assert on

### ISSUE THREAD

**Issue by punkisdead** [punkisdead/lein-cucumber#1]
The cucumber scenarios used to test the plugin are not properly capturing the output to system out in order to assert upon.

```
java.lang.AssertionError: Assert failed: (.contains (clojure.core/deref result) text)
at cucumber.runtime.clj$assert_output_includes.invokeStatic(cucumber_steps.clj:54)
at cucumber.runtime.clj$assert_output_includes.invoke(cucumber_steps.clj:53)
at cucumber.runtime.clj$eval920$fn__921.invoke(cucumber_steps.clj:88)
at clojure.lang.AFn.applyToHelper(AFn.java:154)
at clojure.lang.AFn.applyTo(AFn.java:144)
at clojure.core$apply.invokeStatic(core.clj:646)
at clojure.core$apply.invoke(core.clj:641)
at cucumber.runtime.clj$add_step_definition$reify__748.execute(clj.clj:83)
at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
at cucumber.runtime.Runtime.runStep(Runtime.java:299)
...
```

**Comment by punkisdead** [comment]
Fixed with commit: https://github.com/punkisdead/lein-cucumber/commit/b7d5a641d0009cc6ad449caae27ab01bad33058b
